services:
  account_db:
    image: postgres
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=accountsdb
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: